server:
  logging:

spring:
  application:
    name: chatapp

  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: "src/main/java"
      exclude: static/**,public/**,resources/**
    livereload:
      enabled: true
      port: 35729
